version: "3"
services:
  db-filler:
    container_name: my5grantester-free5gc-db-filler
    build:
      context: ./my5G-RANTester-Database-Filler/
    volumes:
      - ./data:/app/data
    environment:
      - NUM_DEVICES=${NUM_DEVICES}
    networks:
      default:

networks:
  default:
    external:
      name: "free5gc-docker-v306_default"
